services:
  db:
    image: mariadb:lts
    container_name: piikki_db
    restart: unless-stopped

    secrets:
      - db_root_password

    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: piikki

    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  migration:
    build:
      context: .
      dockerfile: ./db/migration.Dockerfile
    container_name: piikki_db_migration
    restart: 'no'

    depends_on:
      db:
        condition: service_healthy

    secrets:
      - db_root_password 
      - db_app_user
      - db_app_password

    entrypoint: >
      sh -c "
        export ROOT_PASSWORD=$$(cat /run/secrets/db_root_password);
        export APP_USER=$$(cat /run/secrets/db_app_user);
        export APP_PASSWORD=$$(cat /run/secrets/db_app_password);

        mysql -h db -u root -p\"$$ROOT_PASSWORD\" piikki < /db/create_schema.sql;
        mysql -h db -u root -p\"$$ROOT_PASSWORD\" piikki < /db/create_search_index.sql;

        cat /db/create_users.sql | \
        sed -e \"s/APP_USER_PLACEHOLDER/$$APP_USER/g; s/APP_PASSWORD_PLACEHOLDER/$$APP_PASSWORD/g\" | \
        mysql -h db -u root -p\"$$ROOT_PASSWORD\" piikki;
      "

    volumes:
      - ./db:/db

  telegram:
    build:
      context: .
      dockerfile: ./cmd/telegram_bot/Dockerfile
    container_name: piikki_bot
    restart: unless-stopped

    depends_on:
      migration:
        condition: service_completed_successfully 

    secrets:
      - db_app_user
      - db_app_password
      - telegram_token

    entrypoint: >
      sh -c "
        export APP_USER=$$(cat /run/secrets/db_app_user);
        export APP_PASSWORD=$$(cat /run/secrets/db_app_password);
        export TELEGRAM_TOKEN=$$(cat /run/secrets/telegram_token);

        export DATABASE_APP=\"$$APP_USER:$$APP_PASSWORD@tcp(db:3306)/piikki\";
        
        exec telegram-bot
      "

  web_app:
    build:
      context: .
      dockerfile: ./cmd/web_app/Dockerfile
    container_name: piikki_web
    restart: unless-stopped

    depends_on:
      migration:
        condition: service_completed_successfully 

    secrets:
      - db_app_user
      - db_app_password
      - cookie_store_secret
      - google_key
      - google_secret

    entrypoint: >
      sh -c "
        export APP_USER=$$(cat /run/secrets/db_app_user);
        export APP_PASSWORD=$$(cat /run/secrets/db_app_password);

        export COOKIE_STORE_SECRET=$$(cat /run/secrets/cookie_store_secret);

        export GOOGLE_KEY=$$(cat /run/secrets/google_key);
        export GOOGLE_SECRET=$$(cat /run/secrets/google_secret);

        export DATABASE_APP=\"$$APP_USER:$$APP_PASSWORD@tcp(db:3306)/piikki\";
        
        exec web-app
      "

    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certbot/www:/var/www/certbot:ro
      - ./data/certbot/conf:/etc/nginx/ssl:ro
    depends_on:
      web_app:
        condition: service_started

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM;
      while :; do
        certbot renew;
        sleep 12h;
      done"

volumes:
  db_data:
    driver: local

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt

  db_app_user:
    file: ./secrets/db_app_user.txt
  db_app_password:
    file: ./secrets/db_app_password.txt

  telegram_token:
    file: ./secrets/telegram_token.txt

  cookie_store_secret:
    file: ./secrets/cookie_store_secret.txt

  google_key:
    file: ./secrets/google_key.txt
  google_secret:
    file: ./secrets/google_secret.txt

